import About from "@/components/About";
import Header from "@/components/Header";
import Landing from "@/components/Landing";
import Projects from "@/components/Projects";
import Head from "next/head";
import { gql, GraphQLClient } from "graphql-request";
import Contact from "@/components/Contact";
import Sidebar from "@/components/Sidebar";
import { MutableRefObject, useEffect, useRef, useState } from "react";
import NavMenu from "@/components/NavMenu";

interface Props {
  projects: Projects[];
}

export default function Home({ projects }: Props) {
  const [visibleSection, setVisibleSection] = useState<string>("");
  const [navMenuOpen, setNavMenuOpen] = useState<boolean>(false);
  const welcome = useRef() as MutableRefObject<HTMLDivElement>;
  const about = useRef() as MutableRefObject<HTMLDivElement>;
  const project = useRef() as MutableRefObject<HTMLDivElement>;
  const contact = useRef() as MutableRefObject<HTMLDivElement>;

  const getDimensions = (element: HTMLElement) => {
    const { height } = element.getBoundingClientRect();
    const offsetTop = element.offsetTop;
    const offsetBottom = offsetTop + height;

    return {
      height,
      offsetTop,
      offsetBottom,
    };
  };

  const sectionRefs = [
    { section: "Welcome", ref: welcome },
    { section: "About", ref: about },
    { section: "Project", ref: project },
    { section: "Contact", ref: contact },
  ];

  const enableScroll = () => {
    window.onscroll = () => {};
  };
  const disableScroll = () => {
    const scrollTop = document.documentElement.scrollTop;
    const scrollLeft = document.documentElement.scrollLeft;

    window.onscroll = () => {
      window.scrollTo(scrollLeft, scrollTop);
    };
  };

  const handleScroll = () => {
    const scrollPosition = window.scrollY;

    const selected = sectionRefs.find(({ section, ref }) => {
      const element = ref.current;
      if (element) {
        const { offsetBottom, offsetTop } = getDimensions(element);
        return scrollPosition > offsetTop && scrollPosition < offsetBottom;
      }
    });

    if (selected && selected.section !== visibleSection) {
      setVisibleSection(selected.section);
    }
  };

  useEffect(() => {
    window.addEventListener("scroll", handleScroll);
    return () => {
      window.removeEventListener("scroll", handleScroll);
    };
  }, [visibleSection]);

  useEffect(() => {
    welcome.current.scrollIntoView({
      behavior: "smooth",
      block: "start",
    });
    disableScroll();
    setTimeout(() => {
      enableScroll();
    }, 4000);
  }, []);

  return (
    <>
      <Head>
        <title>Yusuf Akçay</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header
        welcome={welcome}
        about={about}
        project={project}
        contact={contact}
        currentPage={visibleSection}
        setNavMenuOpen={setNavMenuOpen}
      />

      <main className="flex">
        <NavMenu
          welcome={welcome}
          about={about}
          project={project}
          contact={contact}
          navMenuOpen={navMenuOpen}
          setNavMenuOpen={setNavMenuOpen}
        />

        {/* left container */}
        <section className=" hidden max-h-screen flex-[0.1]  md:flex ">
          <Sidebar />
        </section>

        {/* main container */}
        <section className="w-full border-[blue] md:flex-[0.8]">
          <div ref={welcome} className="mt-[136px] h-screen scroll-m-[96px]">
            <Landing />
          </div>

          <div ref={about} className="mb-10 mt-5 h-fit scroll-m-[96px]">
            <About />
          </div>

          <div ref={project} className="h-fit scroll-m-[96px] xl:mx-10">
            <Projects projects={projects} />
          </div>

          <div ref={contact} className="p-16">
            <Contact />
          </div>

          <div className="mb-0.5 text-center font-mono text-gray-200/80">
            Designed & Created by Yusuf Akçay
          </div>
        </section>

        {/* right container */}
        <section className="hidden flex-[0.1] md:flex "></section>
      </main>
    </>
  );
}

const client = new GraphQLClient(
  "https://eu-central-1-shared-euc1-02.cdn.hygraph.com/content/clg3l7ldk1d6w01t0h5ds7uwf/master"
);

const QUERY = gql`
  {
    projects {
      title
      slug
      desc
      cover {
        url
      }
      tech
      type
      github
      devStatus
    }
  }
`;
export async function getStaticProps() {
  const { projects }: any = await client.request(QUERY);

  return {
    props: {
      projects,
    },
  };
}
